Create generic caching mechanism
canonical/juju-spell pull request #102
Opened 2023-03-15 05:59 UTC by chanchiwai-ray

This PR extends the existing caching mechanism and defines a cache policy that can be used by any cache object. It should works similarly to the `_stored` in the `ops` framework.

- When run as `juju-spell list-models`
   - **[new]** If cached result exist but the cache is expired (based on the cache policy), it will fetch result from the controller and then save the result to the cache directory.

Reopen #99

2023-03-15 06:37 UTC, esunar requested changes
Overall structure is settling, however I cannot see an expire or delete invalidate function in cache for removing objects from cache manually.

2023-03-15 06:37 UTC, esunar commented on juju_spell/cache.py
> +    def update(self, **kwargs: Any) -> None:
We should not have such method

2023-03-15 06:37 UTC, esunar commented on juju_spell/cache.py
> +    return FileCache
factory should return instance not type

2023-03-15 06:37 UTC, esunar commented on juju_spell/commands/list_models.py
> +        cache = get_cache()(controller.controller_uuid, controller.controller_name)
cache should be created when the object is created

2023-03-15 06:50 UTC, chanchiwai-ray commented on juju_spell/cache.py
> +    def update(self, **kwargs: Any) -> None:
ACK

2023-03-15 06:50 UTC, chanchiwai-ray commented on juju_spell/cache.py
> +    return FileCache
ACK

2023-03-15 06:53 UTC, chanchiwai-ray commented on juju_spell/commands/list_models.py
> +        cache = get_cache()(controller.controller_uuid, controller.controller_name)
I agree. The expected behavour should be like `_stored` in `ops` framework where we create the cache at the very beginning of the app, and pass it down to `async def execute(self, controller, cache):`. But now we don't really have this "beginning", so I put it here. We should revisit this after we refactor the code, or do you have any suggestion?

2023-03-15 06:59 UTC, rgildein requested changes
Couple of small comments, but overall LGTM. I tested it and it's works as intended, however I'm little afraid that we are writing everything to same file and Cache is not designer to have just one connection. What could happens is that multiple commands will write to same file at the same time. Not sure if it could be possible :thinking:. What do you think about using
```bash
.local/share/juju-spell/caches
├── list-models
│   ├── e9fe93a1-b705-4067-8f30-6eec183eeb4f
│   └── e9fe93a8-b705-4067-8f30-6eec183eeb4f
```

2023-03-15 06:59 UTC, rgildein commented on juju_spell/cache.py
> +def get_cache(backend: str = "FileCache") -> Any:
I think that it would be better to use constant for `"FileCache"`, so it can be used in multiple places.

2023-03-15 06:59 UTC, rgildein commented on juju_spell/commands/list_models.py
> +        cache = get_cache()(controller.controller_uuid, controller.controller_name)
I think it would be better to not use `FileCache` as default option or at least specify it here with `get_cache(FILE_CACHE)(...)`. What do you think?

2023-03-15 06:59 UTC, rgildein commented on juju_spell/cache.py
> +def get_cache(backend: str = "FileCache") -> Any:
```suggestion
def get_cache(backend: str = "FileCache") -> "Cache":
```

2023-03-15 07:37 UTC, chanchiwai-ray commented on juju_spell/commands/list_models.py
> +        cache = get_cache()(controller.controller_uuid, controller.controller_name)
I was thinking, after we finish the refactor, this parameter is given by config or cli args, and if they don't provide it, config or cli args should gives the default value. Anyways, this line should be revisited after refactoring since we don't want to create cache instance for each command.

2023-03-15 07:40 UTC, chanchiwai-ray commented
> Couple of small comments, but overall LGTM. I tested it and it's works as intended, however I'm little afraid that we are writing everything to same file and Cache is not designer to have just one connection. What could happens is that multiple commands will write to same file at the same time. Not sure if it could be possible thinking. What do you think about using
> 
> ```shell
> .local/share/juju-spell/caches
> ├── list-models
> │   ├── e9fe93a1-b705-4067-8f30-6eec183eeb4f
> │   └── e9fe93a8-b705-4067-8f30-6eec183eeb4f
> ```

I guess it won't... since the cache file is per controller, and within the controller, the command is sequential, and each `put` or `get` transaction is atomic. So, it shouldn't be read / write by multiple commands. But if it is problem, maybe we need to add locks to the cache.

2023-03-15 07:45 UTC, rgildein commented
> I guess it won't... since the cache file is per controller, and within the controller, the command is sequential, and each `put` or `get` transaction is atomic. So, it shouldn't be read / write by multiple commands at the same time. But if it is problem, maybe we need to add locks to the cache.

Yes, but same controller can be defined twice in one config or one command is running, like upgrade-packages, and in mean time I want to get list of models or maybe status of models. So There are scenarios where we could write to same file at once.

2023-03-15 07:58 UTC, chanchiwai-ray commented
> > I guess it won't... since the cache file is per controller, and within the controller, the command is sequential, and each `put` or `get` transaction is atomic. So, it shouldn't be read / write by multiple commands at the same time. But if it is problem, maybe we need to add locks to the cache.
> 
> Yes, but same controller can be defined twice in one config or one command is running, like upgrade-packages, and in mean time I want to get list of models or maybe status of models. So There are scenarios where we could write to same file at once.

In this case, we probably want to use `threading.Lock()` instead of spliting multiple caching files. Because otherwise we will need to create the cache object ourself inside the command, which may not be a good developing experience.

2023-03-15 08:04 UTC, chanchiwai-ray commented on juju_spell/cache.py
> +def get_cache(backend: str = "FileCache") -> Any:
ACK

2023-03-15 08:06 UTC, chanchiwai-ray commented on juju_spell/cache.py
> +def get_cache(backend: str = "FileCache") -> Any:
ACK

2023-03-15 08:08 UTC, rgildein commented
In `sqlite` it would not be much problem, because you will have separate database for each command and here my suggestion is only to not store everything in one file, that's all.

2023-03-15 09:04 UTC, chanchiwai-ray commented on juju_spell/cache.py
> +def get_cache(backend: str = "FileCache") -> Any:
If I define this, and add a property in `FileCache`, mypy does not like it 
```
lint run-test: commands[2] | mypy .
juju_spell/commands/list_models.py:29: error: "Cache" has no attribute "expired"  [attr-defined]
```

2023-03-15 09:19 UTC, chanchiwai-ray commented on juju_spell/commands/list_models.py
> +        cache = get_cache()(controller.controller_uuid, controller.controller_name)
ACK

2023-03-15 09:20 UTC, chanchiwai-ray commented
> In `sqlite` it would not be much problem, because you will have separate database for each command and here my suggestion is only to not store everything in one file, that's all.

Okay, that make sense. I've updated it to create cache directory per command and per controller

2023-03-16 06:32 UTC, esunar requested changes
Only missing remove. Can you look [this](https://pastebin.canonical.com/p/kCbvn3ZMY9/) as reference. This is 2 interface definitions from well known java spring framework.

2023-03-16 06:32 UTC, esunar commented on juju_spell/cache.py
> +    """A cache for command's output with cache policy."""
Still we do not have a way to remove item from cache.

2023-03-16 06:35 UTC, chanchiwai-ray commented on juju_spell/cache.py
> +    """A cache for command's output with cache policy."""
I implemented it in the `FileCache`, but did not specify in `Cache`

2023-03-16 07:14 UTC, rgildein commented on juju_spell/commands/list_models.py
> +        cache: Any = use_cache(DEFAULT_CACHE_BACKEND)
```suggestion
        cache: Cache = use_cache(DEFAULT_CACHE_BACKEND)
```

2023-03-16 07:16 UTC, chanchiwai-ray commented on juju_spell/commands/list_models.py
> +        cache: Any = use_cache(DEFAULT_CACHE_BACKEND)
```
lint run-test: commands[2] | mypy .
juju_spell/commands/list_models.py:28: error: "Cache" has no attribute "check_expired"  [attr-defined]
Found 1 error in 1 file (checked 42 source files)
```
Do you know how to fix it?

2023-03-16 07:22 UTC, rgildein reviewed
Is this right approach? If cache does not exist we are pretending that cache exists.
```bash
(.venv) x1:➜  juju-spell git:(add-generic-cache-mechanism) rm -rf ~/.local/share/juju-spell/caches
(.venv) x1:➜  juju-spell git:(add-generic-cache-mechanism) ll ~/.local/share/juju-spell/            
total 8.0K
-rwxr-xr-x 1 rgildein rgildein 5.7K Mar 10 07:33 config.yaml                                                                         [0.00s]
(.venv) x1:➜  juju-spell git:(add-generic-cache-mechanism) juju-spell list-models --filter owner=Frodo
Use --refresh option with this command to see the latest information.

(Last updated: 2023-03-16 08:17:48)

u1:
- controller
- cos-lite
- default
- exporters
- lma
u2:
- controller
- cos-lite
- default
- exporters
- lma                                                                                                                                [3.94s]
```

not-blocking: Also I think it would be better to have `list-models` sub-directory instead of prefix in file name. 
`./ListModelsCommand_e9fe93a8-b705-4067-8f30-6eec183eeb4f` -> `./ListModelsCommand/e9fe93a8-b705-4067-8f30-6eec183eeb4f`.

2023-03-16 07:24 UTC, rgildein commented on juju_spell/commands/list_models.py
> +        cache: Any = use_cache(DEFAULT_CACHE_BACKEND)
`check_expired` should be in `Cache`? Or we only expect `FileCache` here? If yes, it should be type `FileCache` and not `Any`.

2023-03-16 08:04 UTC, chanchiwai-ray commented
> Is this right approach? If cache does not exist we are pretending that cache exists.
> 
> ```shell
> (.venv) x1:➜  juju-spell git:(add-generic-cache-mechanism) rm -rf ~/.local/share/juju-spell/caches
> (.venv) x1:➜  juju-spell git:(add-generic-cache-mechanism) ll ~/.local/share/juju-spell/            
> total 8.0K
> -rwxr-xr-x 1 rgildein rgildein 5.7K Mar 10 07:33 config.yaml                                                                         [0.00s]
> (.venv) x1:➜  juju-spell git:(add-generic-cache-mechanism) juju-spell list-models --filter owner=Frodo
> Use --refresh option with this command to see the latest information.
> 
> (Last updated: 2023-03-16 08:17:48)
> 
> u1:
> - controller
> - cos-lite
> - default
> - exporters
> - lma
> u2:
> - controller
> - cos-lite
> - default
> - exporters
> - lma                                                                                                                                [3.94s]
> ```

Fixed, it's just the formatting issue, the content is fetched from the controller if it does not has the cache.


> not-blocking: Also I think it would be better to have `list-models` sub-directory instead of prefix in file name. `./ListModelsCommand_e9fe93a8-b705-4067-8f30-6eec183eeb4f` -> `./ListModelsCommand/e9fe93a8-b705-4067-8f30-6eec183eeb4f`.

The file name is simply the `key` in `cache.put(key, data)`. Currently, I don't have a good idea how to originize the cache directory (I think it's not important because normally it's not expected to be seen by end users) without breaking the `Cache` interface. i.e.

```python
# Expected cache interface
------------------------------------
# somewhere not in the `command.execute` and maybe globally defined `from ... import cache`
cache = use_cache(some_backend)
------------------------------------
# in the `command.execute`
def execute(self, controller):
    ...
    key = f"{self.name}_{controller.controller_uuid}"
    cache.put(key, data)
    data = cache.get(key)
    cache.delete(key) # remove the cache file
    ...

# if we organize the cache directory, the cache should somehow know the command name to begin with
------------------------------------
# in the `command.execute`
def execute(self, controller):
    key = f"{controller.controller_uuid}"
    cache = use_cache(some_backend, self.name)
    cache.put(key, data)
    data = cache.get(key)
    cache.delete(key) # remove the cache file

```

2023-03-16 08:05 UTC, chanchiwai-ray commented on juju_spell/commands/list_models.py
> +        cache: Any = use_cache(DEFAULT_CACHE_BACKEND)
Added to `Cache` as a optional method

2023-03-17 08:38 UTC, rgildein commented on juju_spell/cache.py
> +AVALIABLE_BACKENDS = {"FileCache"}
not-blocking: 
```suggestion
AVALIABLE_BACKENDS = {DEFAULT_CACHE_BACKEND}
```

2023-03-20 06:20 UTC, esunar approved these changes

2023-03-20 13:30 UTC, rgildein approved these changes
LGTM, however there are no unit tests for cache and I think we should add it to be able to reach 100% coverage.

2023-03-21 04:42 UTC, chanchiwai-ray commented
Added unittests with 100% coverage for `cache.py`

2023-03-21 08:24 UTC, merged