rename username to user & enable empty model in model_mapping
canonical/juju-spell pull request #12
Opened 2023-01-18 22:11 UTC by rgildein

- rename username to user in config
- enable empty model name for model_mapping in config

2023-01-19 02:19 UTC, jneo8 requested changes
Do we also need to update the cli arguement from username to user?

2023-01-19 08:10 UTC, rgildein commented
> Do we also need to update the cli arguement from username to user?

I was also thinking about it, but I think it make sense only when someone is copy-pasting from juju configs to juju-spell config.

2023-01-19 08:15 UTC, esunar approved these changes

2023-01-20 07:51 UTC, esunar approved these changes

2023-01-20 08:03 UTC, merged