remove VersionCMD
canonical/juju-spell pull request #13
Opened 2023-01-18 22:28 UTC by rgildein

After discussion, we came to the conclusion that the version should be displayed only when `--version' is used and the `version' command should display the version of the controller and not the juju-spell.

I'll add `VersionCMD` back in next PR, but it will return version of controller.

2023-01-19 02:20 UTC, jneo8 requested changes
Maybe a short unit test for `_run_dispatcher`

2023-01-19 08:15 UTC, rgildein commented
> Maybe a short unit test for `_run_dispatcher`

I created #15 issue to add 100% coverage, but you are right I should not be lazy to create `test_cmd.py` and add test for `_run_dispatcher`. :+1:

2023-01-19 15:38 UTC, rgildein commented
Example of usage: https://pastebin.ubuntu.com/p/tjYn7dBDW6/

During making this changes I hit an issue ([lp#1998783](https://bugs.launchpad.net/juju/+bug/1998783)) in Juju.

2023-01-20 07:53 UTC, esunar approved these changes

2023-01-20 08:03 UTC, merged