prepare LXD environemnt (client + 2 controllers)
canonical/juju-spell pull request #34
Opened 2023-02-02 07:39 UTC by rgildein

2023-02-09 12:09 UTC, rgildein commented
Not included in this PR:

- [ ] README.md for functional tests with explanation
- [ ] configure GitHub workflow

2023-02-09 12:29 UTC, esunar requested changes

2023-02-09 12:29 UTC, esunar commented on tests/functional/conftest.py
> +    for dependence in dependencies:
dependence -> dependency

2023-02-09 12:29 UTC, esunar commented on tests/functional/setup_lxd.py
> +        if instance.name.startswith(CONTAINER_PREFIX):
We should create a unique string for each run

2023-02-14 13:44 UTC, rgildein commented on tests/functional/conftest.py
> +    for dependence in dependencies:
I think that bout are valid expressions. Do we really need to switch here?

2023-02-14 17:27 UTC, rgildein commented
I added README.md and configured GH workflows in #52.

Examples of usage with `--no-build` and `--keep-env`.

2023-02-14 17:49 UTC, esunar requested changes

2023-02-14 17:49 UTC, esunar commented on tests/functional/conftest.py
> +    for dependence in dependencies:
just because everyone uses dependency like dependency injection

2023-02-14 17:49 UTC, esunar commented on tests/functional/setup_lxd.py
> +                    instance.status_code != 102
can you define a constant for 102

2023-02-14 17:49 UTC, esunar commented on tests/functional/test_connection.py
> +    assert help_default.exit_code == 127
can you define a constant for 127

2023-02-14 17:49 UTC, esunar commented on tests/functional/setup_lxd.py
> +    sleep(5)  # TODO: we need to wait for container to be fully readyx
Random sleeps!! Can we make it a function to run a simple command on container until it succeeds?

2023-02-14 19:16 UTC, esunar commented
Can you also update Makefile

2023-02-15 05:14 UTC, jneo8 commented on tests/functional/conftest.py
> +    for dependence in dependencies:
dependence is abstract whereas dependency is more concrete

2023-02-15 08:11 UTC, rgildein commented on tests/functional/setup_lxd.py
> +    sleep(5)  # TODO: we need to wait for container to be fully readyx
I put TODO there and forgot to do anything about it. I'll create function.

2023-02-15 17:25 UTC, esunar approved these changes

2023-02-15 17:26 UTC, merged