easy commands
canonical/juju-spell pull request #36
Opened 2023-02-03 08:48 UTC by esunar

2023-02-03 13:01 UTC, rgildein requested changes

2023-02-03 13:01 UTC, rgildein commented on juju_spell/cli/__init__.py
> +from .base import JujuReadCMD, JujuWriteCMD
We should import these here, but instead of that we should use full import where is needed. e.g. `from juju_spell.cli.base import JujuReadCMD, JujuWriteCMD`.
Importing in init make sense to simplify imports, e.g. `from juju_spell.cli.ping import PingCMD` -> `from juju_spell.cli import PingCMD`.

2023-02-04 15:01 UTC, esunar commented on juju_spell/cmd.py
> +def get_all_subclasses(cls):
done

2023-02-06 12:10 UTC, rgildein reviewed
One suggestion.

2023-02-06 12:14 UTC, rgildein approved these changes
LGTM

2023-02-06 14:40 UTC, merged