Initial version of update packages
canonical/juju-spell pull request #44
Opened 2023-02-09 13:58 UTC by esunar

2023-02-10 08:58 UTC, rgildein commented on docs/update_packages-retval.json
> +[
same ^

2023-02-10 08:58 UTC, rgildein commented on juju_spell/commands/update_packages.py
> +        default_model = kwargs["controller_config"].model_mapping["default"]
Why we want to run this only on default model? Why not using `--models` or all models?

2023-02-10 08:58 UTC, rgildein commented on juju_spell/commands/update_packages.py
> +        juju_status_map = await StatusCommand.execute(
I think it would be simpler to run:
```python
model = controller.get_model(<model_name>)
model.connect()
status = model.get_status()
model.disconnect()
```

2023-02-10 08:58 UTC, rgildein commented on juju_spell/commands/update_packages.py
> +            for app, app_status in juju_status.applications.items():
Can we use `model.applications` and than `model.application[<app>].units` to get units, instead of getting it from status?

2023-02-10 10:03 UTC, esunar commented on juju_spell/commands/update_packages.py
> +        updates = self.get_patch_config(kwargs)
fix

2023-02-10 10:09 UTC, esunar commented on juju_spell/commands/update_packages.py
> +        juju_status_map = await StatusCommand.execute(
fixed

2023-02-10 10:10 UTC, esunar commented on juju_spell/commands/update_packages.py
> +        default_model = kwargs["controller_config"].model_mapping["default"]
will be done in future

2023-02-10 10:10 UTC, esunar commented on docs/update_packages-input.json
> +{
they should be as is but needs to be referenced

2023-02-10 10:10 UTC, esunar commented on docs/update_packages-retval.json
> +[
they should be as is but needs to be referenced

2023-02-21 10:28 UTC, rgildein requested changes
One nitpick and one change request comment. Do we want to add unit tests here? Can we provide example of usage? Thanks

2023-02-21 10:28 UTC, rgildein commented on juju_spell/cli/update_packages.py
> +            p = PackageToUpdate(
nitpick: can we rename it from `p` -> `package_to_update`

2023-02-21 10:28 UTC, rgildein commented on juju_spell/commands/update_packages.py
> +        return await self.make_updates(controller=controller, models=models, **kwargs)
I think you missed `dry_run=True` here.

2023-02-21 10:29 UTC, rgildein commented on juju_spell/commands/update_packages.py
> +        default_model = kwargs["controller_config"].model_mapping["default"]
In that case can we report it as issue? So we will not forgot about it. Thanks

2023-02-21 10:31 UTC, rgildein commented on docs/update_packages-input.json
> +{
I think we should put them at least in sub-folder, something like 'commands/update-packages'. When we create our spec we can reference to that.

2023-02-21 11:40 UTC, esunar commented on docs/update_packages-input.json
> +{
/docs/commands/update-packages or /commands/update-packages ?

2023-02-21 11:41 UTC, esunar commented on juju_spell/commands/update_packages.py
> +        default_model = kwargs["controller_config"].model_mapping["default"]
This is implemented

2023-02-21 11:42 UTC, esunar commented on juju_spell/commands/update_packages.py
> +        return await self.make_updates(controller=controller, models=models, **kwargs)
it is in kwargs if I add it will create duplicate variable error

2023-02-21 16:51 UTC, rgildein commented on docs/update_packages-input.json
> +{
`docs/commands/update-packages` I think

2023-02-21 16:52 UTC, esunar commented on juju_spell/cli/update_packages.py
> +            p = PackageToUpdate(
done

2023-02-21 16:56 UTC, rgildein commented on juju_spell/commands/update_packages.py
> +        return await self.make_updates(controller=controller, models=models, **kwargs)
I see, Do you think that we should pop it from kwargs in assignment or here? It's not obvious that here and I think that we should run `self.make_updates` fir `dry_run=True` argument.

2023-02-21 17:07 UTC, esunar commented on juju_spell/commands/update_packages.py
> +        return await self.make_updates(controller=controller, models=models, **kwargs)
can you check again

2023-02-21 17:09 UTC, esunar commented on docs/update_packages-input.json
> +{
done

2023-02-21 17:22 UTC, rgildein requested changes
One question (potentially change request), one nitpick comment and I think you need to remove empty file `generate-config.py`.

2023-02-21 17:22 UTC, rgildein commented on juju_spell/commands/update_packages.py
> +        model_mapping: Dict[str, List[str]],
The `model_mapping` can be `None` as we found out recently if I'm not wrong?

2023-02-21 17:22 UTC, rgildein commented on juju_spell/commands/update_packages.py
> +            n = name.strip(" ")
nitpick: I really think we should avoid using variables like this. Here there are used in next line, but if not it's hard to track what is going on, when I see `tv` variable. It's tv show? :D

2023-02-21 20:19 UTC, esunar commented on juju_spell/commands/update_packages.py
> +        model_mapping: Dict[str, List[str]],
it can be empty cannot be none

2023-02-21 20:23 UTC, esunar commented on juju_spell/commands/update_packages.py
> +            n = name.strip(" ")
done

2023-02-21 20:24 UTC, esunar commented
Also empty file removed

2023-02-23 07:46 UTC, rgildein commented on juju_spell/commands/update_packages.py
> +        model_mapping: Dict[str, List[str]],
Empty means None, or not?

2023-02-23 07:52 UTC, rgildein reviewed
We are still missing unit tests for `juju_spell/commands/update_packages.py`, but otherwise LGTM.

2023-02-23 07:52 UTC, rgildein commented on scripts/generate-config.py
> -#!/usr/bin/env python3
Now I'm confused, last time I saw this as empty file and now it's not.

2023-02-23 09:14 UTC, jneo8 reviewed
Leave 1 suggestion

2023-02-23 09:16 UTC, esunar commented on juju_spell/commands/update_packages.py
> +        model_mapping: Dict[str, List[str]],
[]

2023-02-23 14:40 UTC, esunar commented on juju_spell/commands/update_packages.py
> +        template = UPDATE_TEMPLATE + ("--dry-run" if dry_run else "")
added tests

2023-02-23 17:16 UTC, esunar commented on scripts/generate-config.py
> -#!/usr/bin/env python3
fixed

2023-02-23 18:48 UTC, rgildein requested changes

2023-02-23 18:48 UTC, rgildein commented on juju_spell/commands/update_packages.py
>              from_version = from_version.strip("()[]")
not-blocking: I think we can move this to separate function.

2023-02-23 18:48 UTC, rgildein commented on juju_spell/commands/update_packages.py
> +        model_mapping: Dict[str, List[str]],
I'm confused, because in this [line](https://github.com/canonical/juju-spell/blob/2833ae4686034cb31d6c66aaaa0d53cd8e3dae55/juju_spell/commands/base.py#L139) we are checking if `model_mapping` is `None`, but we are using `model_mapping: Dict[str, List[str]]` everywhere.

2023-02-23 18:48 UTC, rgildein commented on juju_spell/commands/update_packages.py
> +                if re.match(update.name_expr, app):
What will happens if in patch file I use application, which does not exists? It will be quietly ignored?

I think that we can create issue for this and for check that unit exists (check my previous comment).

2023-02-23 18:48 UTC, rgildein commented on juju_spell/commands/update_packages.py
> +                    juju_unit = model.units[unit.unit]
If unit does not exist, the KeyError will be raised and that will not provide good information to user (hard to debug).

I think that we can report an issue for this and handle it in separate PR.

2023-02-23 18:48 UTC, rgildein commented on juju_spell/commands/update_packages.py
> +            name = name.strip(" ")
I think we can move this to the separate function.

2023-02-23 18:48 UTC, rgildein commented on juju_spell/commands/update_packages.py
> +        real_set = [(p.to_version, p.package) for p in unit.packages]
nitpick: I think we should avoid using single character variable name, even in list comprehension.

2023-02-23 18:48 UTC, rgildein commented on juju_spell/commands/update_packages.py
> +        real_set = [(p.to_version, p.package) for p in unit.packages]
You missed one `set` and you do not need to use list comprehension here. `set` will handle the generator
```suggestion
        expected_set = set((e.version, e.package) for e in expected)
        real_set = set((p.to_version, p.package) for p in unit.packages)
```

2023-02-23 18:48 UTC, rgildein commented on tests/unit/cli/test_cli_update_packages.py
> +def test_get_patch_config(tmp_path, input_yaml):
Function `load_patch_file` should be mocked here, so if that function failed only one test will failed.

2023-02-23 18:48 UTC, rgildein commented on tests/unit/cli/test_cli_update_packages.py
> +import argparse
not-blocking: The name of test file do not need to be named `test_cli_*`, since we are using `cli` sub-folder.

2023-02-23 18:48 UTC, rgildein commented on tests/unit/commands/test_update_packages.py
> +@pytest.fixture
not-blocking: It's common practice to use `conftest.py` for defining any fixtures.

2023-02-23 18:49 UTC, rgildein commented
Can you also provide description for this PR + some example how did you tested it. Thanks

2023-02-24 07:10 UTC, esunar commented on juju_spell/commands/update_packages.py
> +                if re.match(update.name_expr, app):
I do not think it is a problem, it is a feature. Because I want to update all prometheus applications I do not care if exits or not. In results it will show updated packages as empty.

2023-02-24 07:11 UTC, esunar commented on juju_spell/commands/update_packages.py
> +                    juju_unit = model.units[unit.unit]
We get unit names from juju in set_apps_to_update. There is not such option.

2023-02-24 07:12 UTC, esunar commented on juju_spell/commands/update_packages.py
> +        real_set = [(p.to_version, p.package) for p in unit.packages]
I agree but in limited scope like comprehensions it does no harm

2023-02-24 07:17 UTC, esunar commented on tests/unit/cli/test_cli_update_packages.py
> +import argparse
The other files were like these to I follow the structure

2023-02-24 07:18 UTC, esunar commented on tests/unit/commands/test_update_packages.py
> +@pytest.fixture
Bu these fixtures are specific to this file.

2023-02-24 15:15 UTC, closed without merging