[WIP] Fix/dry run
canonical/juju-spell pull request #48
Opened 2023-02-10 10:10 UTC by jneo8

2023-02-14 17:35 UTC, rgildein reviewed
Can you rebase this, since #46 was merged? Also can you provide example of output in CLI.

I think only one small suggestion here.

2023-02-14 17:35 UTC, rgildein commented on juju_spell/assignment/runner.py
> +            output = await command.run(controller=controller, **command_kwargs)
```suggestion
        elif parsed_args.dry_run:
            output = await command.dry_run(controller=controller, **command_kwargs)
        else:
            output = await command.run(controller=controller, **command_kwargs)
```

2023-02-15 02:08 UTC, jneo8 commented on juju_spell/assignment/runner.py
> +            output = await command.run(controller=controller, **command_kwargs)
The suggestion is not what we want because the flow should be

*pre-check* -> (if error) -> *return*
*pre-check* -> (if not error) -> *dry-run* or *run*

2023-02-15 08:23 UTC, rgildein commented on juju_spell/assignment/runner.py
> +            output = await command.run(controller=controller, **command_kwargs)
if `pre-check` failed nothing else should be called.

2023-02-15 10:12 UTC, esunar approved these changes

2023-02-15 10:21 UTC, rgildein requested changes
Can you provide example of output. Thanks

2023-02-15 10:21 UTC, rgildein commented on juju_spell/assignment/runner.py
> +                output = await command.run(controller=controller, **command_kwargs)
```python
if pre_check is not None:
    output = pre_check
elif parsed_args.dry_run:
    output = await command.dry_run(controller=controller, **command_kwargs)
else:
    output = await command.run(controller=controller, **command_kwargs)
```

2023-02-15 15:29 UTC, jneo8 commented
> Can you provide example of output. Thanks

Where you want me to provide it? In the doc-string or PR.
I am a little bit confuse what you really want.

2023-02-15 17:02 UTC, rgildein commented
> > Can you provide example of output. Thanks
> 
> Where you want me to provide it? In the doc-string or PR. I am a little bit confuse what you really want.

Since there is no functional test yet, we should always give examples that our changes work and how they work.
Example #46.

2023-02-16 05:10 UTC, jneo8 commented
> > > Can you provide example of output. Thanks
> > 
> > 
> > Where you want me to provide it? In the doc-string or PR. I am a little bit confuse what you really want.
> 
> Since there is no functional test yet, we should always give examples that our changes work and how they work. Example #46.

Update

2023-02-16 06:34 UTC, jneo8 commented
@esunar  Can we merge this one?

2023-02-16 07:46 UTC, rgildein approved these changes

2023-02-16 07:49 UTC, merged