model_mapping improvements
canonical/juju-spell pull request #55
Opened 2023-02-14 17:33 UTC by esunar

Changed controllers.model_mapping to Dict[str, List[str]] thus we will be able to add more than one model as default

get_filtered_models now handles the model_mapping

2023-02-14 18:01 UTC, rgildein requested changes

2023-02-14 18:01 UTC, rgildein commented on juju_spell/commands/base.py
>                  await model.disconnect()
Next suggestion, after seeing we already supports the list of models in model_mapping.

```python
    @staticmethod
    async def _filter_models(
        controller: Controller,
        model_mappings: Dict[str, List[str]],
        models: Optional[List[str]] = None,
    ) -> List[str]:
        """Return filtered list of models names."""
        if models is None:
            return await controller.list_models()

        filtered_models = []
        for model in models:
            filtered_models.extend(model_mappings.get(model, [model]))

        return filtered_models

    @staticmethod
    async def get_filtered_models(
        controller: Controller,
        model_mappings: Dict[str, List[str]],
        models: Optional[List[str]] = None,
    ) -> AsyncGenerator[Tuple[str, Model], None]:
        """Get filtered models for controller.

        If models is None, then all models for controller will be returned.
        """
        filtered_models = await _filter_models(controller, model_mappings, models)
        
        for model_name in filtered_models:
            model = await controller.get_model(model_name)
            yield model_name, model
            await model.disconnect()
```

2023-02-14 18:56 UTC, esunar commented on juju_spell/commands/base.py
> +    return None
added docstring

2023-02-15 07:49 UTC, jneo8 requested changes

2023-02-15 07:49 UTC, jneo8 commented on juju_spell/commands/base.py
> +        model_mappings: Dict[str, List[str]],
**suggestion:** I will say it's hard for me to first time understand what is model_mapping and what is models.

I think a docstring here to provide more details will be really helpful.

2023-02-15 07:49 UTC, jneo8 commented on juju_spell/commands/base.py
> +def _filter_models(
**nitpick:** 

The naming of the function and what it really does is not match.
Maybe we need to know it's more about model mapping?

2023-02-15 07:49 UTC, jneo8 commented on juju_spell/commands/status.py
> +            controller, models, kwargs["controller_config"].model_mapping
**issue:** 
What if model_mapping doesn't exists?
We don't provide the default for model_mapping so it will raise KeyError

2023-02-15 07:49 UTC, jneo8 commented on juju_spell/commands/base.py
> +    models: List[str], model_mappings: Dict[str, List[str]]
**issue:** 

The type annotation of model_mapping is not correct.
Should be `Optional[Dict[str, List[str]]]`

2023-02-15 08:18 UTC, rgildein commented on juju_spell/commands/status.py
> +            controller, models, kwargs["controller_config"].model_mapping
The `model_mapping` is required in config, so it will be there.

2023-02-15 08:19 UTC, rgildein commented on juju_spell/commands/base.py
> +    models: List[str], model_mappings: Dict[str, List[str]]
Since `model_mapping` is required I do not think this is needed.

2023-02-15 08:22 UTC, rgildein reviewed
Can you add unit tests for `_filter_models` function? I think it's useful to tests also function like this.

2023-02-15 08:22 UTC, rgildein commented on juju_spell/commands/base.py
> +    if model_mappings is None or len(model_mappings) <= 0:
Since we have right now two required keys (`lma` and `default`) in `model_mapping` it's not needed to check len.

2023-02-15 10:09 UTC, esunar commented on juju_spell/commands/base.py
> +    if model_mappings is None or len(model_mappings) <= 0:
removed

2023-02-15 10:22 UTC, rgildein approved these changes
LGTM

2023-02-16 07:03 UTC, merged