feat(juju_spell/config.py): Create default configuration options
canonical/juju-spell pull request #57
Opened 2023-02-15 03:35 UTC by jneo8

2023-02-15 06:12 UTC, esunar approved these changes
I seems ok

2023-02-15 06:17 UTC, esunar requested changes
controller1: 30
controller2: 20
controller3: 43

personal.controller > global.controller > personel.default > global.default

personal.config
default:
  timeout: 20
controller1
  timeout: 30
controller2
controller3


global.config
default:
  timeout: 21
controller1
  timeout: 24
controller2
controller3
  timeout: 43

2023-02-15 07:19 UTC, jneo8 commented
> I could not see the most extensive `codeconstant < global.default.config < global.config < local.default.config < local.config ` test.

We have tests for *apply_default*, *merge_config* and *load_config*.
The logic been hidden behind those three function.
It's possible if we don't patch any them to create this test. Do you think we need this one?

2023-02-15 10:14 UTC, esunar approved these changes

2023-02-15 10:49 UTC, rgildein requested changes
I think that this will not work properly, can you add unit test to simulate
```yaml
default:
  controller:
    connection:
      timeout: 30
controllers:
- name: 1
  ...
- name: 2
  ...
  connection:
    destination: 1.2.3.4
    timeout: 20
- name: 3
  ...
  connection:
    destination: 1.2.3.4
```
30s is expected timeout for c1 anc c3, for c2 it should be 20. However I think c3 will lost connection.destination.

2023-02-15 10:49 UTC, rgildein commented on juju_spell/config.py
> +        valid_config = _config.get(template)
nitpick: can we add debug message here? It will be useful.

2023-02-15 10:49 UTC, rgildein commented on juju_spell/config.py
> +        target_key = key + "s"
Do we really want to use something like this? what if target key is not list? Why not using "controllers" directly?

2023-02-15 10:49 UTC, rgildein commented on juju_spell/config.py
> +                {**value, **target_value} for target_value in source[target_key]
Will this work properly? If we define
```yaml
default:
  controller: 
    connection:
      timeout: 5
```
it will override whole connection in each controller.

2023-02-15 15:27 UTC, jneo8 commented on juju_spell/config.py
> +        valid_config = _config.get(template)
I am not sure what kind of debug message you want. It will raise error if not validated. It's either error or no output. I don't think this is needed.

2023-02-15 15:27 UTC, jneo8 commented on juju_spell/config.py
> +                {**value, **target_value} for target_value in source[target_key]
Ye, this is a bug. I need to figure out how to fix it.

2023-02-15 17:08 UTC, rgildein commented on juju_spell/config.py
> +        target_key = key + "s"
Where and how? I think that ring now our config file has strict format, so why adding strange magic, which is working only for controllers now.
If any new target come, we will need to update our template and if that target is not list we will need to create new rule how it will be updated, so I do not see any reason why creating it like this now.

2023-02-15 20:06 UTC, rgildein requested changes
I tried this with simple config:
```yaml
default:
  controller:
    user: rgildein
controllers:
- uuid: ...
  user: admin
- uuid: ...
  # no user defined
```
And I got an error 
```bash
configuration file validation failed with error: default.controller must be a list, not dict 
```

Can you test the functionality and provide example of your `config.yaml` and `personal.yaml`.
Thanks

2023-02-16 05:59 UTC, jneo8 commented
> I tried this with simple config:
> 
> ```yaml
> default:
>   controller:
>     user: rgildein
> controllers:
> - uuid: ...
>   user: admin
> - uuid: ...
>   # no user defined
> ```
> 
> And I got an error
> 
> ```shell
> configuration file validation failed with error: default.controller must be a list, not dict 
> ```
> 
> Can you test the functionality and provide example of your `config.yaml` and `personal.yaml`. Thanks

Fixed. The example is already in doc.

2023-02-16 16:20 UTC, merged