Refactor/connection config
canonical/juju-spell pull request #58
Opened 2023-02-15 07:12 UTC by jneo8

Move connection from top layer info controller's config.

2023-02-19 16:52 UTC, esunar approved these changes

2023-02-19 19:20 UTC, rgildein requested changes
Small fix required.

2023-02-19 19:20 UTC, rgildein commented on juju_spell/config.py
> +                    "port_range": confuse.Optional(
this should be `port-range`

2023-02-20 06:27 UTC, jneo8 commented on juju_spell/config.py
> +                    "port_range": confuse.Optional(
There are two reasons I change all `port-range` to `port_range`.

1. Same format for all the config. We use variables with underscore like `ca_cert`, `display_name`, etc. But we only use dash for `port-range`.
2. Because we use confuse to load yaml and load it into python's datacalss. Confuse seems not covert dash to underscore for us, which should be a basic behavior for python's configuration library, unfortunately confuse is not in the role. So to have a *clear* definition in python's dataclass, we need to change it to underscore.

2023-02-20 08:33 UTC, esunar commented on juju_spell/config.py
> +                    "port_range": confuse.Optional(
I agree with @jneo8 to compatible with python standards it would be good to be underscore.

2023-02-20 08:38 UTC, rgildein commented on juju_spell/config.py
> +                    "port_range": confuse.Optional(
My bad, I thought that in code you used `port-range`, but you renamed it everywhere.
Yes we need to use `_` for those, because we are passing it to dataclass object, where we could not have `port-range` as variable.

2023-02-20 10:21 UTC, rgildein approved these changes
LGTM

2023-02-20 11:01 UTC, merged