add controller connect w/ exponential retries
canonical/juju-spell pull request #6
Opened 2023-01-17 19:35 UTC by rgildein

- move defining `self.connections[controller_config.name]` before controller connect
- add retry function for controller w/ exponential retries
- fix empty controller_name and controller_uuid when connection without JUJU_DATA

2023-01-18 07:21 UTC, esunar requested changes

2023-01-18 07:21 UTC, esunar commented on juju_spell/connections/manager.py
> +    wait: float = 1.5
This should come from config
global config->local config->controller config->default

2023-01-18 07:21 UTC, esunar commented on juju_spell/connections/manager.py
> +CONENCTION_TIMEOUT = 60  # seconds
This should come from config
global config->local config->controller config->default

2023-01-18 07:53 UTC, esunar requested changes

2023-01-18 07:53 UTC, esunar commented on juju_spell/connections/manager.py
> +            wait = 1.5 ** (attempt - 2)  # exponential wait 1.5^(x-2)
It should be constant

2023-01-19 18:14 UTC, rgildein commented on juju_spell/connections/manager.py
> +    wait: float = 1.5
Right now I moved everything to `settings.py` and I reported an issue #21, so that we can implement it as we discussed.

2023-01-20 07:52 UTC, esunar approved these changes

2023-01-20 08:04 UTC, merged