[WIP] Feat/retry conn config
canonical/juju-spell pull request #64
Opened 2023-02-20 08:03 UTC by jneo8

2023-02-20 13:49 UTC, esunar reviewed
recheck

2023-02-21 01:18 UTC, jneo8 commented
recheck

2023-02-21 06:43 UTC, esunar requested changes
Configuration config need change on the functional tests. As I far I test everything seems to be ok. Can you also fix the functional tests.

2023-02-21 06:43 UTC, esunar commented on setup.cfg
> +    tenacity
can you add this to requirements.txt

2023-02-21 07:15 UTC, esunar approved these changes

2023-02-21 10:40 UTC, rgildein commented on setup.cfg
> +    tenacity
Why we have requirements.txt? I though we are using only setup.cfg for requirements.

I checked that requirements.txt is used only in snapcraft.yaml and I will remove it. There is no reason to have requirement in two places.

2023-02-21 11:08 UTC, rgildein requested changes
Couple of small comments + we need to fix something, because func tests are failing. (ping command failed with this [error](https://github.com/canonical/juju-spell/actions/runs/4230183083/jobs/7347339916#step:6:747))

2023-02-21 11:08 UTC, rgildein commented on juju_spell/connections/conn_builder.py
> +            before=_before_log(uuid=uuid, name=name),
These two lines do not make sense to me, because you are calling function here and they log those messages now. They are no callable object for later usage.

2023-02-22 03:33 UTC, jneo8 commented on juju_spell/connections/conn_builder.py
> +import typing as t
This is a common way to use `typing` library.

2023-02-22 03:34 UTC, jneo8 commented on juju_spell/connections/conn_builder.py
> +    from tenacity.wait import WaitBaseT
It's for mypy's typing check, which we don't have now, it won't have any effort here.

2023-02-22 03:38 UTC, jneo8 commented on juju_spell/connections/conn_builder.py
> +            before=_before_log(uuid=uuid, name=name),
Those are customized log functions.
Instead of writing log every where, put it here it more fit how to use tenacity.

2023-02-22 03:43 UTC, jneo8 commented on setup.cfg
> +    tenacity
> I checked that requirements.txt is used only in snapcraft.yaml

I think that is the reason we add it here.
What are you planing to remove?
And I think not matter the change you want to have, we can change it in another separate PR about snapcraft dependency.

2023-02-22 03:57 UTC, jneo8 commented on setup.cfg
> +    tenacity
Oh I saw your PR: https://github.com/canonical/juju-spell/pull/67

Then I think this is resolved, we can fix it in your PR.

2023-02-22 06:09 UTC, esunar reviewed
recheck

2023-02-22 06:29 UTC, esunar commented
Functional tests run on my local machine however it gets "craft_providers.bases.errors.BaseCompatibilityError: Incompatible base detected: Expected OS 'Ubuntu', found None." it github runners. @rgildein can you take a look. I could not see anything wrong in the workflow file.

2023-02-22 08:57 UTC, rgildein commented on juju_spell/connections/conn_builder.py
> +import typing as t
I do not like it, because
- it's not used anywhere in our repos
- instead of importing what you need you are creating alias with single character

This is not blocking, but I do not like it.

2023-02-22 09:02 UTC, rgildein commented on juju_spell/connections/conn_builder.py
> +    from tenacity.wait import WaitBaseT
I know what `TYPE_CHECKING` represents, but I do not know why these imports should not be executed.

2023-02-22 09:06 UTC, rgildein commented on juju_spell/connections/conn_builder.py
> +            before=_before_log(uuid=uuid, name=name),
```python
def _after_log():
  logger.info("after")

def _before_log():
  logger.info("before")

Test(a=1,b=2,c=3,after=_after_log(), before=_before_log())
# at this point both function will be executed <==> both logs will be emitted
```

You are executing those helper function at the same time during class initialization, tenecity will not execute this before and after each retry. Is my point clear here?

2023-02-22 09:15 UTC, rgildein commented
> Functional tests run on my local machine however it gets "craft_providers.bases.errors.BaseCompatibilityError: Incompatible base detected: Expected OS 'Ubuntu', found None." it github runners. @rgildein can you take a look. I could not see anything wrong in the workflow file.

It's working for me locally also (snapcraft pack), so I just re-trigger the tests.

2023-02-22 09:20 UTC, jneo8 commented on juju_spell/connections/conn_builder.py
> +            before=_before_log(uuid=uuid, name=name),
Oh, it's my mistake.
It should return a callable function.

2023-02-22 09:20 UTC, jneo8 commented on juju_spell/connections/conn_builder.py
> +            before=_before_log(uuid=uuid, name=name),
updated

2023-02-22 09:23 UTC, rgildein commented on juju_spell/connections/conn_builder.py
> +            before=_before_log(uuid=uuid, name=name),
or simply use `lambda: logger.info(...)`

2023-02-22 09:41 UTC, esunar approved these changes

2023-02-22 11:22 UTC, jneo8 commented on juju_spell/connections/conn_builder.py
> +import typing as t
I don't think we will have conclusion here. We can find people discuss about two different ways' pros and cons here: https://github.com/mesonbuild/meson/issues/6333

2023-02-22 11:27 UTC, jneo8 commented on juju_spell/connections/conn_builder.py
> +    from tenacity.wait import WaitBaseT
Sorry I misunderstanding your question.

I think the major reason is to resolve import cycles.

2023-02-22 11:35 UTC, rgildein commented on juju_spell/connections/conn_builder.py
> +    from tenacity.wait import WaitBaseT
> I think the major reason is to resolve import cycles.

You mean that tenacity will import something from our source code?

There is no need to have this, so I do not see reason why have it here.

2023-02-22 11:38 UTC, rgildein commented on juju_spell/connections/conn_builder.py
> +import typing as t
Yes, but we should stay uniform and if you prefer this solution we should use it at least everywhere in this repo.

2023-02-22 11:38 UTC, rgildein reviewed
recheck

2023-02-22 11:43 UTC, jneo8 commented on juju_spell/connections/conn_builder.py
> +    from tenacity.wait import WaitBaseT
Updated

2023-02-22 11:43 UTC, jneo8 commented on juju_spell/connections/conn_builder.py
> +import typing as t
Updated

2023-02-22 12:04 UTC, rgildein approved these changes
LGTM
I was waiting for func test to pass [:green_circle:](https://github.com/canonical/juju-spell/actions/runs/4242313636/jobs/7373757935)

2023-02-22 16:11 UTC, merged