update to current bootstack template
canonical/juju-spell pull request #78
Opened 2023-02-27 15:08 UTC by rgildein

- update to current BootStack templates
- fix linting with mypy and pylint  

This is base on [MP](https://code.launchpad.net/~rgildein/bootstack-charms-spec/+git/bootstack-charms-spec/+merge/437954).

2023-02-27 15:09 UTC, rgildein commented
The lint checkers are failing, because before I update anything I want to discuss it.

2023-02-28 14:21 UTC, esunar approved these changes

2023-02-28 17:46 UTC, rgildein reviewed
recheck

2023-03-01 03:36 UTC, jneo8 requested changes
Not finish all reviews.
Leave some question.

2023-03-01 03:36 UTC, jneo8 commented on juju_spell/cli/grant.py
> +            help=f"Access control. e.g., {','.join(ACL_CHOICES)}.",
**question:** 

Any reason we need to change to f-string?

2023-03-01 03:36 UTC, jneo8 commented on juju_spell/commands/base.py
> +    async def pre_check(self, controller: Controller, **kwargs: Any) -> Optional[Result]:
**nitpick:** 

I don't get this one. This doesn't provide any information.

```python
def func_x(**kwargs: Any)
```

2023-03-01 03:36 UTC, jneo8 commented on juju_spell/commands/enable_user.py
> +    async def execute(self, controller: Controller, *args: Any, **kwargs: Any) -> bool:
**nitpick:** 

Some as mentioned earlier

2023-03-01 04:02 UTC, jneo8 requested changes

2023-03-01 08:19 UTC, rgildein commented on juju_spell/commands/base.py
> +    async def pre_check(self, controller: Controller, **kwargs: Any) -> Optional[Result]:
mypy

2023-03-01 08:21 UTC, rgildein commented on juju_spell/commands/remove_user.py
> +        self.logger.info("%s user `%s` was successfully removed", controller.controller_uuid, user)
Anything in command should start with controller_uuid, I tried to make it with logger, but it was not possible. It was not possible because craft_cli is not using format function in their logging handler, so for now we need/should do it manually.

2023-03-01 08:22 UTC, rgildein commented on juju_spell/commands/status.py
> +        self, controller: Controller, *args: Any, models: Optional[List[str]] = None, **kwargs: Any
You could not put it after arg with default value.

2023-03-01 08:23 UTC, rgildein commented on juju_spell/config.py
> +    port_range: range = DEFAULT_PORT_RANGE
It should never be None and if it's issue, please report it.

2023-03-01 08:23 UTC, rgildein commented on juju_spell/connections/network.py
> +    def __init__(self) -> None:
mypy

2023-03-01 08:24 UTC, rgildein reviewed
recheck

2023-03-01 09:43 UTC, jneo8 approved these changes

2023-03-01 11:01 UTC, merged