Added juju-spell config.
canonical/juju-spell pull request #86
Opened 2023-03-02 11:28 UTC by esunar

* moved load_yaml_file to utils package
* added unit tests for juju-spell config

note: documentation will be added

2023-03-03 03:43 UTC, chanchiwai-ray commented on tests/unit/cli/test_cli_config.py
> +    assert parser.add_argument.call_count == 7
Just curious, is it really necessary to check these here? Adding more basic arguments in `cli.base` will cause error in here which is not really related to `test_cli_config.py`

2023-03-03 03:51 UTC, chanchiwai-ray commented on tests/unit/cli/test_cli_config.py
> +
Since you implemented a custom `KeyValue` action, I think it's better to include test case for this action. For example, test if `parser.parse_args(['--config-set a=1 b=2 c=cpu=4])` gives you `{"a": 1, "b":2 , "c": "cpu=4"}`

2023-03-03 04:03 UTC, chanchiwai-ray commented on juju_spell/cli/config.py
> +"""JujuSpell juju status command."""
`"""JujuSpell juju status command."""`: maybe copy-and-paste error ?

2023-03-03 04:04 UTC, chanchiwai-ray commented on juju_spell/cli/config.py
> +    """JujuSpell juju status command."""
Same here

2023-03-03 04:11 UTC, chanchiwai-ray commented on juju_spell/commands/config.py
> +logger = logging.getLogger("eeee")
is it intentional ? `logging.getLogger("eeee")` 🤣

2023-03-03 06:36 UTC, jneo8 requested changes

2023-03-03 06:36 UTC, jneo8 commented on juju_spell/commands/config.py
> +logger = logging.getLogger("eeee")
I believe is cat.

2023-03-03 06:36 UTC, jneo8 commented on juju_spell/commands/config.py
> +        async for name, model in self.get_filtered_models(
**thought:** 

Not blocking command.

I am thinking about the comment I gave [here](https://github.com/canonical/juju-spell/issues/83#issuecomment-1451355000)

Iterate over models/application/machine inside command really make thing more complex and hard to understand the working flow.

Just want to point out this is the situation I want to avoid.

2023-03-03 06:36 UTC, jneo8 commented on juju_spell/utils.py
> +def load_yaml_file(path: str) -> Any:
**suggestion:** 

Not blocking.
The code here is similar to `load_config_file` function inside `config.py`.
Consider to have a small refactor here.

2023-03-03 06:36 UTC, jneo8 commented on tests/unit/cli/test_cli_config.py
> +    assert parser.add_argument.call_count == 7
Rather than check add_argument count. I will suggest to actually check the real context give to add_argument.

2023-03-03 11:11 UTC, esunar commented on tests/unit/cli/test_cli_config.py
> +    assert parser.add_argument.call_count == 7
extended checks.
remove call_count check

2023-03-03 11:11 UTC, esunar commented on tests/unit/cli/test_cli_config.py
> +
added tests

2023-03-03 11:11 UTC, esunar commented on juju_spell/cli/config.py
> +"""JujuSpell juju status command."""
fixed doc

2023-03-03 11:11 UTC, esunar commented on juju_spell/cli/config.py
> +    """JujuSpell juju status command."""
fixed doc

2023-03-03 11:11 UTC, esunar commented on juju_spell/commands/config.py
> +logger = logging.getLogger("eeee")
killed the cat :)

2023-03-03 11:29 UTC, rgildein commented on tests/unit/cli/test_cli_config.py
> +    assert parser.add_argument.call_count == 7
It's not important to check which CLI options from BaseCLI, but it's important to check  that there were used.

2023-03-03 11:38 UTC, rgildein requested changes

2023-03-03 11:38 UTC, rgildein commented on juju_spell/cli/config.py
> +# mypy: allow-untyped-defs
We should rather add typing that disabling mypy and pylint.

2023-03-03 11:38 UTC, rgildein commented on juju_spell/commands/config.py
> +async def apply_config(app: Application, properties: Dict[str, str], single_property: str) -> dict:
I do not understand what is this function trying to do. can you add description in docstring with some examples?

2023-03-03 11:38 UTC, rgildein commented on juju_spell/utils.py
> +def load_yaml_file(path: str) -> Any:
I agree we should combine that together. And  having one in utils make sense.

2023-03-03 12:51 UTC, esunar commented on juju_spell/cli/config.py
> +# mypy: allow-untyped-defs
It is impossible to add typing 
```
    def __call__(
        self, parser: ArgumentParser, namespace: Namespace, values: str | Sequence[Any] | None, option_string: str | None = ...
    ) -> None: ...
```
python 3.8 does not support `|`

2023-03-03 13:20 UTC, esunar commented on juju_spell/commands/config.py
> +async def apply_config(app: Application, properties: Dict[str, str], single_property: str) -> dict:
refactored to remove ambigutiy

2023-03-03 13:21 UTC, esunar commented on juju_spell/utils.py
> +def load_yaml_file(path: str) -> Any:
combined

2023-03-03 13:29 UTC, rgildein commented on juju_spell/cli/config.py
> +# mypy: allow-untyped-defs
`from typing import Optional`

2023-03-04 19:55 UTC, esunar commented on juju_spell/cli/config.py
> +# mypy: allow-untyped-defs
mypy does not like it either

2023-03-06 07:35 UTC, rgildein commented on juju_spell/cli/config.py
> +# mypy: allow-untyped-defs
That's strange it's should be other issue.

2023-03-06 09:01 UTC, jneo8 approved these changes

2023-03-06 12:33 UTC, rgildein commented on juju_spell/cli/config.py
> +# mypy: allow-untyped-defs
Can you share the output from mypy.

2023-03-06 12:47 UTC, rgildein commented on juju_spell/cli/config.py
> +# mypy: allow-untyped-defs
```python
class KeyValue(argparse.Action):
    """Parse parameters as key=value pairs."""

    def __call__(
        self,
        _: argparse.ArgumentParser,
        namespace: argparse.Namespace,
        values: Union[str, Sequence[Any], None],
        option_string: Optional[str] = None,
    ) -> None:
        setattr(namespace, self.dest, {})
        if values:
            for value in values:
                key, value = value.split("=", 1)
                getattr(namespace, self.dest)[key] = value
```
And from this it's obvious that you could not assume that values is None or List of strings, it cloud be also only string.

2023-03-07 02:14 UTC, chanchiwai-ray approved these changes

2023-03-07 07:31 UTC, esunar commented on juju_spell/cli/config.py
> +# mypy: allow-untyped-defs
applied your recommendation result:
`juju_spell/cli/config.py:134:0: R0903: Too few public methods (1/2) (too-few-public-methods)`

2023-03-07 21:38 UTC, esunar commented on tests/unit/cli/test_cli_config.py
> +    assert parser.add_argument.call_count == 7
extended checks

2023-03-07 21:39 UTC, esunar commented on juju_spell/cli/config.py
> +# mypy: allow-untyped-defs
fixed the issue by bypassing too-few-public-methods for python3.8

2023-03-08 06:56 UTC, rgildein requested changes
2 small things, but otherwise LGTM

2023-03-08 06:56 UTC, rgildein commented on juju_spell/cli/config.py
> +# pylint: disable=too-few-public-methods
this is not needed

2023-03-08 06:56 UTC, rgildein commented on juju_spell/utils.py
> +logger = logging.getLogger()
It's better to use new logger, which will inherit from root rather than using root logger.
```suggestion
logger = logging.getLogger(__name__)
```

2023-03-08 06:56 UTC, rgildein commented on tests/unit/cli/test_cli_config.py
> +def test_add_mutually_exclusive_group_parameters() -> None:
not-blocking: define return value for tests function is not needed `-> None`

2023-03-08 06:57 UTC, rgildein commented on juju_spell/cli/config.py
> +# mypy: allow-untyped-defs
Now I can see that you are hitting still this issue, wired that for me w/ Python3.10 is working.

2023-03-08 07:03 UTC, rgildein commented on juju_spell/cli/config.py
> +# mypy: allow-untyped-defs
Can you share version of pylint and argparse you are using?

2023-03-08 07:14 UTC, rgildein commented on juju_spell/cli/config.py
> +# mypy: allow-untyped-defs
I tried it on Python3.8 and lint is not working due the fact that pylxd is not supported, but with some tweak I got same error from pylint. Strange, I do not understand why. Resolving this.

2023-03-08 12:58 UTC, rgildein approved these changes
LGTM

2023-03-08 14:58 UTC, merged