feat(juju_spell/commands/add_user.py): Grant user permission when acl…
canonical/juju-spell pull request #87
Opened 2023-03-03 05:59 UTC by jneo8

- Call grant cmd in add-user cmd if `acl` is in the params.
- Grant cmd now will grant model permission for user.

2023-03-03 06:35 UTC, chanchiwai-ray reviewed
LGTM

2023-03-03 11:51 UTC, rgildein requested changes

2023-03-03 11:51 UTC, rgildein commented on juju_spell/commands/add_user.py
> +                return grant_result
I think at this point we should raise an error and not return grand result.

2023-03-03 11:51 UTC, rgildein commented on juju_spell/commands/grant.py
> +            controller_acl = "login"
We should not silently change the acl value here, since the validation is done in CLI it should never be anything else and if yes than it should raise an error.

2023-03-03 11:51 UTC, rgildein commented on juju_spell/commands/grant.py
> +            controller_acl = "login"
If we are trying to do some default values, than it should be like `if acl is None` or even better is `kwargs.get("acl", "login")`

2023-03-03 11:51 UTC, rgildein commented on juju_spell/commands/grant.py
> +            model_acl = "read"
similar situation here

2023-03-03 11:51 UTC, rgildein commented on juju_spell/commands/grant.py
> +                return grant_model_result
There is no log message or any logic how differed between output from this process. I mean if i saw `False` I will not not why it's false. Can you some logs and maybe change it to return Result object with success = True/False and message which models was granted and which not? What do you think>?

2023-03-03 11:51 UTC, rgildein commented on tests/unit/commands/conftest.py
> +async def _async_generator(values: List) -> AsyncGenerator:
not-blocking: This is not a fixtures, so I'll suggest to move it to tests/unit/utils.py.

2023-03-04 14:12 UTC, esunar requested changes

2023-03-04 14:12 UTC, esunar commented on juju_spell/commands/add_user.py
> +            grant_cmd = GrantCommand()
Don't we also need enable_user and grand_model?

2023-03-06 03:10 UTC, jneo8 commented on juju_spell/commands/grant.py
> +            controller_acl = "login"
> We should not silently change the acl value here, since the validation is done in CLI it should never be anything else and if yes than it should raise an error.

Here is the command, so we are not change the value.

Because we are grant user's acl to model and controller in the same time.

The acl value can be either model permission in [`read`, `write`, `admin`] or controller permission in [`superuser`, `login`]. The idea is user only need to type one of the acl then we will generate the correspond acl for user in both model and controller.

2023-03-06 03:11 UTC, jneo8 commented on juju_spell/commands/grant.py
> +                return grant_model_result
We can add log msg here.

2023-03-06 03:13 UTC, jneo8 commented on juju_spell/commands/add_user.py
> +            grant_cmd = GrantCommand()
The grant model is been include in GrantCommand.

The enable_user is losing. I will add this.

2023-03-06 03:13 UTC, jneo8 commented on juju_spell/commands/add_user.py
> +                return grant_result
Ack

2023-03-06 07:47 UTC, rgildein commented on juju_spell/commands/grant.py
> +            controller_acl = "login"
We should at-least moved this logic to separate function or make it simpler, because like this we have too many if statements.

2023-03-06 07:47 UTC, rgildein commented on juju_spell/commands/grant.py
> +            )
I'm not sure if we should failed here or not. Maybe here yes and if grant to model failed not? What do you think @jneo8 and @esunar ? From user perspective.

2023-03-06 10:07 UTC, jneo8 commented on juju_spell/commands/grant.py
> +            )
Updated.

After I checked the python-libjuju. It will raise error from the lib directly. So I remove the raise part here.

2023-03-06 10:12 UTC, jneo8 commented on tests/unit/commands/conftest.py
> +async def _async_generator(values: List) -> AsyncGenerator:
Ack

2023-03-06 12:49 UTC, rgildein commented on juju_spell/commands/add_user.py
> +                return grant_result
How this will help to user? You will return only `output = False` why?

2023-03-06 12:55 UTC, rgildein commented on juju_spell/commands/grant.py
> +        return True
It's not related to this PR, but maybe we could define that each commands should return Result object. In this case Something like Result(success=True, output="permission were granted for user %s in controller %s and following models %s"). What do you think @jneo8 and @esunar? Same to all commands, so we can easily aggregate results form multiple commands.

2023-03-06 12:58 UTC, rgildein commented on juju_spell/commands/grant.py
> +            )
Is that behavior which we want? If grant permission for single model failed (model is broken or I do not know) we will end up with user, which have permission only for some models

2023-03-07 01:11 UTC, jneo8 commented on juju_spell/commands/grant.py
> +        return True
Ack. unify log format is helpful.

2023-03-07 01:17 UTC, jneo8 commented on juju_spell/commands/grant.py
> +            )
In the newest commit. We provide a argument `--overwrite`. It will ignore the exception and continue to next step, otherwise will get exception.

2023-03-07 01:18 UTC, jneo8 commented on juju_spell/commands/grant.py
> +            model_acl = "read"
Updated

2023-03-07 01:18 UTC, jneo8 commented on juju_spell/commands/grant.py
> +            controller_acl = "login"
Updated

2023-03-07 01:20 UTC, jneo8 commented on juju_spell/commands/add_user.py
> +                return grant_result
Not, the output will be `Result(success=False, error=${error-here})`.
Because the `run` function will return Result object, so it is simple logic to return the Result object from grant cmd.

2023-03-07 10:53 UTC, esunar requested changes

2023-03-07 10:53 UTC, esunar commented on juju_spell/commands/grant.py
> +            controller.uuid,
controller does not have uuid

2023-03-07 10:53 UTC, esunar commented on juju_spell/commands/grant.py
> +                model.uuid,
controller does not have uuid

2023-03-07 12:44 UTC, esunar commented on juju_spell/commands/grant.py
> +            controller.uuid,
```suggestion
            controller.controller_uuid,
```

2023-03-07 12:45 UTC, esunar commented on juju_spell/commands/grant.py
> +                controller.uuid,
```suggestion
                controller.controller_uuid,
```

2023-03-07 20:54 UTC, esunar approved these changes

2023-03-08 07:41 UTC, rgildein requested changes

2023-03-08 07:41 UTC, rgildein commented on juju_spell/commands/add_user.py
> +        except JujuError as err:
This is not good validation that user exist, because adding user could failed for other reason. You can check these [lines](https://github.com/juju/python-libjuju/blob/master/juju/controller.py#L649-L654). In fact it would be better to use `controller.get_user` instead of try and except here.

2023-03-08 07:41 UTC, rgildein commented on juju_spell/commands/add_user.py
> +            )
we should add log message with information that user was added

2023-03-08 07:41 UTC, rgildein commented on juju_spell/commands/add_user.py
> +                await user.set_password(password)  # Reset user's password
we should add log message that user password was changed

2023-03-08 07:41 UTC, rgildein commented on juju_spell/commands/add_user.py
> +                    raise err
Why this is needed? Can you provide some notes here, because we are not catching some specific error or can we make it more specific? The `controller.grant` is already doing some catching in these [lines](https://github.com/juju/python-libjuju/blob/master/juju/controller.py#L649-L654).

2023-03-08 07:41 UTC, rgildein commented on juju_spell/commands/enable_user.py
> +                raise err
Again this catching needs to be improved.

2023-03-08 07:41 UTC, rgildein commented on juju_spell/commands/enable_user.py
> +            await controller.enable_user(username=kwargs["user"])
We should add some logs here.

2023-03-08 07:41 UTC, rgildein commented on juju_spell/commands/grant.py
> +                raise err
Again this exception is to generous, you do not know why it's failing.

2023-03-08 09:25 UTC, rgildein commented on juju_spell/commands/add_user.py
> +                return grant_result
You change it, but before the grant command was not catching any error.

2023-03-08 12:52 UTC, jneo8 commented on juju_spell/commands/grant.py
> +                raise err
grant model will fail if the permission is exists.

2023-03-08 12:53 UTC, jneo8 commented on juju_spell/commands/add_user.py
> +                    raise err
Ack. This one can be remove

2023-03-08 12:53 UTC, jneo8 commented on juju_spell/commands/add_user.py
> +                await user.set_password(password)  # Reset user's password
Ack

2023-03-08 12:53 UTC, jneo8 commented on juju_spell/commands/add_user.py
> +            )
Ack

2023-03-08 12:54 UTC, jneo8 commented on juju_spell/commands/add_user.py
> +        except JujuError as err:
Ack

2023-03-08 12:56 UTC, rgildein commented on juju_spell/commands/grant.py
> +                raise err
Yes it will failed if permission exists, but it can failed if your user could not grant permission or something went wrong with controller or ... . The `JujuError` could mean a lot of other things.

2023-03-08 13:19 UTC, jneo8 commented
Reopen in #93

2023-03-08 13:19 UTC, closed without merging