feat(remove-user): remove user now disable user and revoke permission only
canonical/juju-spell pull request #90
Opened 2023-03-06 11:50 UTC by jneo8

2023-03-06 13:57 UTC, esunar approved these changes

2023-03-08 02:50 UTC, chanchiwai-ray requested changes
Thanks for the patch, overall looks good to me, but I do left some non-blocking comments / suggestions.

2023-03-08 02:50 UTC, chanchiwai-ray commented on juju_spell/commands/enable_user.py
> +__all__ = ["EnableUserCommand", "DisableUserCommand"]
Maybe I missed the initial discussion about the code architeture. What is the reason for putting two commands in one single file ? Why can't we have separate file for disable user command ?

2023-03-08 02:50 UTC, chanchiwai-ray commented on juju_spell/commands/enable_user.py
> +        await controller.enable_user(username=kwargs["user"])
non-blocking: If enable user command now returns None, we may also want to update docstring in `cli.enable_user`.

2023-03-08 02:50 UTC, chanchiwai-ray commented on juju_spell/commands/revoke.py
> +        return True
Is it possible to return False? e.g. for a non-existing user.

2023-03-08 02:50 UTC, chanchiwai-ray commented on juju_spell/commands/revoke.py
> +        return True
Is it possible to return False? e.g. for a non-existing user.

2023-03-08 02:50 UTC, chanchiwai-ray commented on tests/unit/utils.py
> +async def _async_generator(values: List) -> AsyncGenerator:
Naming suggestion: since it's used somewhere else (i.e. not private function), we should remove the prefix `_`.

2023-03-08 07:53 UTC, rgildein requested changes

2023-03-08 07:53 UTC, rgildein commented on juju_spell/commands/enable_user.py
> +__all__ = ["EnableUserCommand", "DisableUserCommand"]
On the contrary, I think that we can move all commands for user to single file, so AddUser, RemoveUser, EnableUser, DisableUser, GrantUser. Otherwise we will have so many files with simple command like 5 lines EnableUserCommand in separate files.

2023-03-08 07:53 UTC, rgildein commented on juju_spell/commands/enable_user.py
> +        await controller.enable_user(username=kwargs["user"])
Why we are not returning anything here? Since `controller.enable_user` functions is returning something we should return that value.

2023-03-08 07:53 UTC, rgildein commented on juju_spell/commands/enable_user.py
> +        *args: Any,
not-related: When I was adding mypy and pylint, I thought that we can change signature for BaseJujuCommand so function execute will not take any positional argument -> `*args: Any` will not be needed. What do you think?

2023-03-08 07:53 UTC, rgildein commented on juju_spell/commands/enable_user.py
> +    async def execute(self, controller: Controller, *args: Any, **kwargs: Any) -> None:
Can you also use `user: Optional[str] = None,` here.

2023-03-08 07:53 UTC, rgildein commented on juju_spell/commands/enable_user.py
> +        await controller.disable_user(username=user)
Again why not returning output from `controller.disable_user` function?

2023-03-08 07:53 UTC, rgildein commented on juju_spell/commands/enable_user.py
> +__all__ = ["EnableUserCommand", "DisableUserCommand"]
But here it does not make sense to have `DisableUserCommand` in `enable_user.py`.

2023-03-08 07:53 UTC, rgildein commented on juju_spell/commands/revoke.py
> +        return True
Again why we are not return result from `controller.revoke` function?

2023-03-08 13:22 UTC, jneo8 commented on juju_spell/commands/enable_user.py
> +    async def execute(self, controller: Controller, *args: Any, **kwargs: Any) -> None:
Maybe `user: str` is more exactly. It's required.

2023-03-08 13:23 UTC, jneo8 commented on juju_spell/commands/enable_user.py
> +        await controller.disable_user(username=user)
After I checking the `python-libjuju`. The return data is nothing important.

2023-03-08 13:24 UTC, jneo8 commented
Re-open in #93

2023-03-08 13:24 UTC, closed without merging