Add caching feature to list models
canonical/juju-spell pull request #92
Opened 2023-03-08 07:08 UTC by chanchiwai-ray

This MR add caching capability to `list-models` sub-command. It (ideally) contains the following feature:

- When run as `juju-spell list-models`
  - It tries to load the cached result of `list-models` from `DEFAULT_CACHE_DIR`, and if not found, it will fetch result from the controller and then save the result to the cache directory.
  - If cached result exist, it use the cache result and prepend a warning message to instruct user to run `--refresh` if necessary.
- When run as `juju-spell list-models --refresh`
  -  It will fetch result from the controller and then save the result to the cache directory.

However, due to #89 , the caching feature currently does not improve the speed significantly.

2023-03-08 09:38 UTC, rgildein requested changes
Two comments. I just want to confirmed that we change the design from using cached list of models (e.g. dealing with cache in `get_filtered_model_names`) to have cache for whole commands.

I think it's good idea, but we should move the mechanism to the BaseJujuCommand or to BaseJujuCachedCommand, so it will be easily re-usable. Not in this PR.

2023-03-08 09:38 UTC, rgildein commented on juju_spell/commands/list_models.py
> +        return JujuSpellError(error_message_template.format(uuid, str(error)))
I think that this should raise an error or return None if cache does not exists.

2023-03-08 09:38 UTC, rgildein commented on juju_spell/commands/list_models.py
> +def save_cache_data(
I think that we should have this function predefined in units, so we can use it in multiple places and format will be same.
```python
cache_data = {
        "uuid": controller.controller_uuid,
        "name": controller.controller_name,
        "data": {
           "models": models,
           "refresh": refresh,
        },
        "timestamp": time(),
    }
```
What do you think?

2023-03-08 10:07 UTC, chanchiwai-ray commented on juju_spell/commands/list_models.py
> +        return JujuSpellError(error_message_template.format(uuid, str(error)))
ACK

2023-03-08 10:07 UTC, chanchiwai-ray commented on juju_spell/cli/list_models.py
> +        (Last updated: 1970-01-01 00:00:00)
No reason, this date just come to my mind 😆 , change to the date Canonical founded.

2023-03-08 10:08 UTC, chanchiwai-ray commented on juju_spell/cli/list_models.py
> +    "Use --refresh option with this command to see the latest information.\n\n(Last updated: {})"
ACK

2023-03-08 10:12 UTC, chanchiwai-ray commented on juju_spell/commands/list_models.py
> +def save_cache_data(
I think having a common format for `cached_data` is a good idea, but I currently do not have a complete picture of how are we going to use it (`cache_data`) in other places. I think we can keep it this way until there's more commands that can use `cache_data`.

2023-03-08 10:23 UTC, chanchiwai-ray commented
Thanks for the comments. Initially, I was thinking about only cache a list of models, but I realized that there are not many context about the models (e.g. from which controller, when did we create the cache, and how do we name the cache file, etc.). So, I decided to add more contexts, and in the end, it looks that I am caching for the whole commands (status, info, models) for a given controller.

I currently do not think we should put it `BaseJujuCommand` or deals with cache in `get_filtered_model_names`. This is because many commands could go wrong if we used an outdated `cache` (e.g. if we want to change user's permission of a model using the cache data, but the cache is out of date. It could cause command failed with weird errors, or if we want to list all units, but with a outdated cache...). I think we need more example of using the cache, and then refactor if needed.

2023-03-08 10:34 UTC, rgildein commented on juju_spell/commands/list_models.py
> +def save_cache_data(
Yes, that's true but since we do not have bigger picture and this is used only in one place it make sense to me to use one format in utils.
```python
def save_cache_data(
    controller: Controller, data: Dict[str, Any], logger: Logger
) -> Dict[str, Any]:
    cache_data = {
        "uuid": controller.controller_uuid,
        "name": controller.controller_name,
        "data": data,
        "timestamp": time(),
    }
```
Maybe if we will not be suitable for all scenarios, but that we can fix later and now it will be simpler + it will not force people to use a custom functions.

2023-03-08 10:37 UTC, rgildein commented on juju_spell/utils.py
> +    fname = DEFAULT_CACHE_DIR / uuid
Now I check that we are using only controller uuid in file name, maybe we can use something like `<command_name>-<controller_uuid>`? It's not really needed in this PR.

2023-03-08 10:41 UTC, rgildein commented
> I currently do not think we should put it `BaseJujuCommand` or deals with cache in `get_filtered_model_names`. This is because many commands could go wrong if we used an outdated `cache` (e.g. if we want to change user's permission of a model using the cache data, but the cache is out of date. It could cause command failed with weird errors, or if we want to list all units, but with a outdated cache...). I think we need more example of using the cache, and then refactor if needed.

Yes I agree that it should not be in `BaseJujuCommand`, because we do not want to use cache for each command e.g. update-packages or add-user, but in future we can create `BaseReadJujuCommand`/`BaseCachecJujuCommand`, which will inherit from `BaseJujuCommand` and integrate cache mechanism. We will see, I'm just thinking at lout.

2023-03-08 13:21 UTC, esunar commented on juju_spell/cli/list_models.py
> +                    datetime.fromtimestamp(timestamp).strftime(DATETIME_FORMATTER)
I would prefer timestamp human readable

2023-03-08 13:21 UTC, esunar commented on juju_spell/commands/list_models.py
> +        "name": controller.controller_name,
I do not think we need name here. What will we do if name and uuid differs

2023-03-08 13:21 UTC, esunar commented on juju_spell/utils.py
> +    fname = DEFAULT_CACHE_DIR / uuid
One of the biggest problems of using cache is cache eviction. I we are going to use caching application wise. It deserves own class with explicit policy. Something like:
```python
class JujuSpellCache:
    @abstractmethod
    def get(self, ) -> Any:
        pass

    @abstractmethod
    def put(self, cache) -> bool:
        pass

class CachingPolicy:
    policymap: Dict[str, int] = {} # "[command, timetolive in seconds]"
    ttl: int #timetolive in seconds

class FileCache(JujuSpellCache):
    policy: CachingPolicy

    def get(self, ) -> Any:
        pass

    def put(self, cache) -> bool:
        pass
```

2023-03-09 01:39 UTC, chanchiwai-ray commented on juju_spell/cli/list_models.py
> +                    datetime.fromtimestamp(timestamp).strftime(DATETIME_FORMATTER)
The data in the cache file and in python is timestamp, but when it's printed to the screen it's human readable like `2004-03-04 00:00:00`

2023-03-09 01:42 UTC, chanchiwai-ray commented on juju_spell/commands/list_models.py
> +        "name": controller.controller_name,
`uuid` is used to ID the cache file and provide more context about the cached data, and `name` is used when printing the message. E.g. 

```bash
<controller_name>
- model-a
- model -b
```

2023-03-09 01:46 UTC, chanchiwai-ray commented on juju_spell/utils.py
> +    fname = DEFAULT_CACHE_DIR / uuid
I think policy like this is a good idea. It can be used to auto-refresh the cache if it's expired. Currently, the output message only gives you a warning like `use --refresh to get latest information ... (last updated <datetime>)`, and it's up to the user to refresh it. But with the policy, we can inspect the timestamp and decide if we want to automatically update it or not.

2023-03-09 04:46 UTC, chanchiwai-ray commented on juju_spell/utils.py
> +    fname = DEFAULT_CACHE_DIR / uuid
Updated

2023-03-09 04:47 UTC, chanchiwai-ray commented on juju_spell/utils.py
> +    fname = DEFAULT_CACHE_DIR / uuid
For now, I created simple `Cache` and `CachePolicy` to check if a cache is expired or not, but we can add more feature in the future if necessary.

2023-03-09 05:37 UTC, jneo8 requested changes
Most LGTM. Need to add more log msg.

2023-03-09 05:37 UTC, jneo8 commented on juju_spell/commands/list_models.py
> +        logger.debug(error_message_template, fname, str(error))
**suggestion:** 

logger.warning/error?

Failing msg should be warning level.

2023-03-09 05:37 UTC, jneo8 commented on juju_spell/utils.py
> +    except FileNotFoundError as error:
**suggestion:** 

I will consider to add log message here to tell the user why loading cache is fail. All the exception we know it may happen should have log.

2023-03-09 06:17 UTC, chanchiwai-ray commented on juju_spell/commands/list_models.py
> +        logger.debug(error_message_template, fname, str(error))
Updated

2023-03-09 06:19 UTC, chanchiwai-ray commented on juju_spell/utils.py
> +    except FileNotFoundError as error:
Added loggging when load cache is successful. But I think for the failing part, `craft_cli` will capute the error and we return that in the `Result.error`, so it might not be necessary.

2023-03-09 10:03 UTC, rgildein commented on juju_spell/cli/list_models.py
> +                    datetime.fromtimestamp(timestamp).strftime(DATETIME_FORMATTER)
Maybe @esunar mean that we should use human readable in cache file?

2023-03-09 10:03 UTC, rgildein commented on juju_spell/utils.py
> +class CachePolicy(dict):
This should be in next PR.

2023-03-09 10:03 UTC, rgildein commented on juju_spell/utils.py
> +    except FileNotFoundError as error:
We are raising from error so it's should be in log file.

2023-03-09 10:36 UTC, chanchiwai-ray commented on juju_spell/utils.py
> +class CachePolicy(dict):
I agree, I also will put @esunar 's request in next PR about refactoring `save_to_cache` and `load_from_cache` function into a dedicated `FileCache` because it's quite a bit of changes.

2023-03-09 10:38 UTC, chanchiwai-ray commented on juju_spell/utils.py
> +    except FileNotFoundError as error:
yes, it's in the log file if you check it with `--verbosity debug`

2023-03-09 11:01 UTC, esunar commented on juju_spell/cli/list_models.py
> +                    datetime.fromtimestamp(timestamp).strftime(DATETIME_FORMATTER)
I think so

2023-03-10 02:55 UTC, chanchiwai-ray commented on juju_spell/cli/list_models.py
> +                    datetime.fromtimestamp(timestamp).strftime(DATETIME_FORMATTER)
It can, but I would opt to use a timestamp instead of human readable format. Because 1. the cache file is not intended to be read by human (although readble), 2. it's a lot easier to work with timestamp in python if you need to use the timestamp to do calculation e.g. checking if the cache is expired.

2023-03-10 06:30 UTC, rgildein approved these changes
LGTM

2023-03-10 06:35 UTC, rgildein commented on juju_spell/commands/list_models.py
> +def save_cache_data(
I still think that these function would be better only in utils, but since this is first command is not an issue.

2023-03-10 06:40 UTC, merged