Feat/user add remove
canonical/juju-spell pull request #93
Opened 2023-03-08 13:19 UTC by jneo8

#77 

> I squash two PR #87 #90 to this one and also update to address some comments

2023-03-08 14:06 UTC, rgildein requested changes

2023-03-09 01:57 UTC, jneo8 commented on juju_spell/commands/add_user.py
> +        if user is None:  # User exists
Haha, yes your are right

2023-03-09 01:58 UTC, jneo8 commented on juju_spell/commands/enable_user.py
> +__all__ = ["EnableUserCommand", "DisableUserCommand"]
Agree. But in separate.
I can submit that one after this one merge.

2023-03-09 01:58 UTC, jneo8 commented on juju_spell/commands/add_user.py
> +            self.logger.info("Create user %s", kwargs["user"])
Ack

2023-03-09 01:59 UTC, jneo8 commented on juju_spell/commands/add_user.py
> +            self.logger.info("Reset user password")
Ack

2023-03-09 01:59 UTC, jneo8 commented on juju_spell/commands/enable_user.py
> +            self.logger.info("Start enable user %s", kwargs["user"])
Ack

2023-03-09 02:00 UTC, jneo8 commented on juju_spell/commands/enable_user.py
> +                raise err
Ack

2023-03-09 02:04 UTC, jneo8 commented on juju_spell/commands/remove_user.py
> +        revoke_result = await revoke_cmd.run(controller=controller, user=user, acl="login")
Just because we want `RevokeCommand` and `RevokeModelCommand` can be reused later. Right now we don't create cli interface for them.
But merging them together to one revoke is an option.

2023-03-09 07:26 UTC, esunar requested changes

2023-03-09 07:26 UTC, esunar commented on juju_spell/commands/remove_user.py
> +            if not overwrite:
just remove overwrite

2023-03-09 07:26 UTC, esunar commented on juju_spell/commands/remove_user.py
> +        self,
add preheck to operate on own user

2023-03-09 17:27 UTC, esunar approved these changes

2023-03-10 02:50 UTC, chanchiwai-ray approved these changes
Non-blocking, it's a "need information only" comment. Can you prove / disapprove my concern in the inline comment?

2023-03-10 02:50 UTC, chanchiwai-ray commented on juju_spell/cli/add_user.py
> +        if not retval[0]["success"]:
Not sure if it's correct, but I think we should check **any** `retval`  not success, instead of just picking one, because the first one can be successful, and the next one can be not successful. E.g.

```python
for controller_outputs in retval:
    if not controller_outputs["success"]:
        return JujuWriteCMD.format_output(retval)
```

2023-03-10 06:13 UTC, jneo8 commented on juju_spell/cli/add_user.py
> +        if not retval[0]["success"]:
Updated

2023-03-10 06:33 UTC, jneo8 commented on juju_spell/commands/grant.py
> +        self.logger.info(
Updated

2023-03-10 06:42 UTC, rgildein commented on juju_spell/commands/remove_user.py
> +        revoke_result = await revoke_cmd.run(controller=controller, user=user, acl="login")
Creating new command for every single line is only creating overheat, since each command is creating new logger and some other logic, which is not needed here. But ok. Second think I do not understand is why we are not consistent in single PR? Why one command is handling permission for whole controller and all models at the same time and next command is doing it one by one.

2023-03-10 07:00 UTC, jneo8 commented on juju_spell/commands/remove_user.py
> +        revoke_result = await revoke_cmd.run(controller=controller, user=user, acl="login")
Grant have cli interface. revoke doesn't. Again this kind of change should can be in separate PR.

2023-03-10 07:01 UTC, esunar commented
I am merging this PR since it is working as expected. However we should revisit this code after we implement composition of commands.

2023-03-10 07:01 UTC, merged